---
destination : _site
auto        : false
lsi         : false
pygments    : false
permalink   : none
markdown    : rdiscount
markdowns   : rdiscount, pandoc-ruby, maruku
exclude     : ['README.markdown', 'scripts']
url         : http://davidsanson.com
pandoc-ruby :
    number-sections : false
    toc             : false
    from            : markdown
