---
destination : _site
auto        : false
lsi         : false
pygments    : false
permalink   : none
markdown    : rdiscount
markdowns   : pandoc-ruby, rdiscount, maruku
url         : http://davidsanson.com
pandoc-ruby:
    number-sections : false
    toc             : false