destination : _site
auto        : false
lsi         : false
pygments    : false
permalink   : none
markdown    : rdiscount
exclude     : ['README.markdown', 'scripts']
url         : 'http://www.davidsanson.com'
pandoc      :
    extensions : [smart, mathjax]
