webDir = { type: 'dir', contents: {
  'courses': { type: 'dir', contents: {
    'index.html': { type: 'html', url: '/courses/index.html'},
	'101f2009': { type: 'dir', contents: {
    'index.html': { type: 'html', url: '/101f2009/index.html'},
    'readings.html': { type: 'html', url: '/101f2009/readings.html'},
    'syllabus.html': { type: 'html', url: '/101f2009/syllabus.html'},
  }},
  '250s2011': { type: 'dir', contents: {
    'assignments': { type: 'dir', contents: {
      'index.html': { type: 'html', url: '/250s2011/assignments/index.html'},
    }},
    'course-description.html': { type: 'html', url: '/250s2011/course-description.html'},
    'index.html': { type: 'html', url: '/250s2011/index.html'},
    'readings': { type: 'dir', contents: {
      'index.html': { type: 'html', url: '/250s2011/readings/index.html'},
    }},
    'syllabus.html': { type: 'html', url: '/250s2011/syllabus.html'},
    'textbook.html': { type: 'html', url: '/250s2011/textbook.html'},
  }},
  '301f2009': { type: 'dir', contents: {
    'index.html': { type: 'html', url: '/301f2009/index.html'},
    'readings.html': { type: 'html', url: '/301f2009/readings.html'},
    'syllabus.html': { type: 'html', url: '/301f2009/syllabus.html'},
  }},
  '301f2010': { type: 'dir', contents: {
    'about-the-exam.html': { type: 'html', url: '/301f2010/about-the-exam.html'},
    'action-philosophers.html': { type: 'html', url: '/301f2010/action-philosophers.html'},
    'assignments': { type: 'dir', contents: {
      'final-exam-study-guide.html': { type: 'html', url: '/301f2010/assignments/final-exam-study-guide.html'},
      'first-assignment.html': { type: 'html', url: '/301f2010/assignments/first-assignment.html'},
      'index.html': { type: 'html', url: '/301f2010/assignments/index.html'},
      'midterm-study-guide.html': { type: 'html', url: '/301f2010/assignments/midterm-study-guide.html'},
      'second-paper.html': { type: 'html', url: '/301f2010/assignments/second-paper.html'},
    }},
    'bits-and-pieces.html': { type: 'html', url: '/301f2010/bits-and-pieces.html'},
    'bookstore-snafu-update.markdown.html': { type: 'html', url: '/301f2010/bookstore-snafu-update.markdown.html'},
    'bookstore.html': { type: 'html', url: '/301f2010/bookstore.html'},
    'breaking-news.html': { type: 'html', url: '/301f2010/breaking-news.html'},
    'course-description.html': { type: 'html', url: '/301f2010/course-description.html'},
    'extra-office-hour.html': { type: 'html', url: '/301f2010/extra-office-hour.html'},
    'extra-office-hours-and-seis.html': { type: 'html', url: '/301f2010/extra-office-hours-and-seis.html'},
    'index.html': { type: 'html', url: '/301f2010/index.html'},
    'lindsays-office-hours.html': { type: 'html', url: '/301f2010/lindsays-office-hours.html'},
    'philosophy-club.html': { type: 'html', url: '/301f2010/philosophy-club.html'},
    'reading-for-Oct-28.html': { type: 'html', url: '/301f2010/reading-for-Oct-28.html'},
    'readings': { type: 'dir', contents: {
      'aristotle-reading.html': { type: 'html', url: '/301f2010/readings/aristotle-reading.html'},
      'index.html': { type: 'html', url: '/301f2010/readings/index.html'},
      'no-new-readings-for-9-30.html': { type: 'html', url: '/301f2010/readings/no-new-readings-for-9-30.html'},
      'no-new-readings-for-oct-7.html': { type: 'html', url: '/301f2010/readings/no-new-readings-for-oct-7.html'},
      'optional-reading-mentioned-in-class.html': { type: 'html', url: '/301f2010/readings/optional-reading-mentioned-in-class.html'},
      'reading-assignment.html': { type: 'html', url: '/301f2010/readings/reading-assignment.html'},
      'reading-for-09-28.html': { type: 'html', url: '/301f2010/readings/reading-for-09-28.html'},
      'reading-for-nov-2.html': { type: 'html', url: '/301f2010/readings/reading-for-nov-2.html'},
      'reading-for-oct-12.html': { type: 'html', url: '/301f2010/readings/reading-for-oct-12.html'},
      'reading-for-oct-5.html': { type: 'html', url: '/301f2010/readings/reading-for-oct-5.html'},
      'reading-list.html': { type: 'html', url: '/301f2010/readings/reading-list.html'},
      'readings-for-Nov-18th.html': { type: 'html', url: '/301f2010/readings/readings-for-Nov-18th.html'},
      'readings-for-oct-14.html': { type: 'html', url: '/301f2010/readings/readings-for-oct-14.html'},
      'readings-for-oct-19.html': { type: 'html', url: '/301f2010/readings/readings-for-oct-19.html'},
      'some-optional-readings-on-parmenides.html': { type: 'html', url: '/301f2010/readings/some-optional-readings-on-parmenides.html'},
    }},
    'syllabus.html': { type: 'html', url: '/301f2010/syllabus.html'},
    'textbook.html': { type: 'html', url: '/301f2010/textbook.html'},
    'this-course-is-done.html': { type: 'html', url: '/301f2010/this-course-is-done.html'},
    'useful-secondary-sources.html': { type: 'html', url: '/301f2010/useful-secondary-sources.html'},
    'zenos-paradoxes.html': { type: 'html', url: '/301f2010/zenos-paradoxes.html'},
  }},
  '463w2010': { type: 'dir', contents: {
    'assignments': { type: 'dir', contents: {
      'first-assignment.html': { type: 'html', url: '/463w2010/assignments/first-assignment.html'},
      'index.html': { type: 'html', url: '/463w2010/assignments/index.html'},
      'second-assignment.html': { type: 'html', url: '/463w2010/assignments/second-assignment.html'},
    }},
    'handouts': { type: 'dir', contents: {
      'changehandout.html': { type: 'html', url: '/463w2010/handouts/changehandout.html'},
      'index.html': { type: 'html', url: '/463w2010/handouts/index.html'},
    }},
    'index.html': { type: 'html', url: '/463w2010/index.html'},
    'news': { type: 'dir', contents: {
      'due-feb-10.html': { type: 'html', url: '/463w2010/news/due-feb-10.html'},
      'due-mar-10.html': { type: 'html', url: '/463w2010/news/due-mar-10.html'},
      'first-assn.html': { type: 'html', url: '/463w2010/news/first-assn.html'},
      'for-feb-10.html': { type: 'html', url: '/463w2010/news/for-feb-10.html'},
      'for-feb-17.html': { type: 'html', url: '/463w2010/news/for-feb-17.html'},
      'for-feb-22.html': { type: 'html', url: '/463w2010/news/for-feb-22.html'},
      'for-feb-3.html': { type: 'html', url: '/463w2010/news/for-feb-3.html'},
      'for-jan-11.html': { type: 'html', url: '/463w2010/news/for-jan-11.html'},
      'for-jan-20.html': { type: 'html', url: '/463w2010/news/for-jan-20.html'},
      'for-jan-25.html': { type: 'html', url: '/463w2010/news/for-jan-25.html'},
      'for-jan-6.html': { type: 'html', url: '/463w2010/news/for-jan-6.html'},
      'for-mar-3.html': { type: 'html', url: '/463w2010/news/for-mar-3.html'},
      'handoutposted.html': { type: 'html', url: '/463w2010/news/handoutposted.html'},
      'index.html': { type: 'html', url: '/463w2010/news/index.html'},
      'study-questions.html': { type: 'html', url: '/463w2010/news/study-questions.html'},
    }},
    'readings.html': { type: 'html', url: '/463w2010/readings.html'},
    'study_questions.html': { type: 'html', url: '/463w2010/study_questions.html'},
    'syllabus.html': { type: 'html', url: '/463w2010/syllabus.html'},
  }},
  '670f2010': { type: 'dir', contents: {
    'assignments': { type: 'dir', contents: {
      'grade-scale-for-first-homework.html': { type: 'html', url: '/670f2010/assignments/grade-scale-for-first-homework.html'},
      'homework-assignment.html': { type: 'html', url: '/670f2010/assignments/homework-assignment.html'},
      'index.html': { type: 'html', url: '/670f2010/assignments/index.html'},
      'paper-topics.html': { type: 'html', url: '/670f2010/assignments/paper-topics.html'},
      'second-assignment.html': { type: 'html', url: '/670f2010/assignments/second-assignment.html'},
    }},
    'course-description.html': { type: 'html', url: '/670f2010/course-description.html'},
    'course-done.html': { type: 'html', url: '/670f2010/course-done.html'},
    'discuss': { type: 'dir', contents: {
      'handout.html': { type: 'html', url: '/670f2010/discuss/handout.html'},
      'impeccability.html': { type: 'html', url: '/670f2010/discuss/impeccability.html'},
      'index.html': { type: 'html', url: '/670f2010/discuss/index.html'},
      'power-and-ability.html': { type: 'html', url: '/670f2010/discuss/power-and-ability.html'},
      'week-1.html': { type: 'html', url: '/670f2010/discuss/week-1.html'},
    }},
    'god-bipolar.html': { type: 'html', url: '/670f2010/god-bipolar.html'},
    'god-man-vs-human-man.html': { type: 'html', url: '/670f2010/god-man-vs-human-man.html'},
    'index.html': { type: 'html', url: '/670f2010/index.html'},
    'off-campus-links.html': { type: 'html', url: '/670f2010/off-campus-links.html'},
    'on-turning-the-paper-in.html': { type: 'html', url: '/670f2010/on-turning-the-paper-in.html'},
    'readings': { type: 'dir', contents: {
      'index.html': { type: 'html', url: '/670f2010/readings/index.html'},
      'lewis-on-the-necessity-of-the-past.html': { type: 'html', url: '/670f2010/readings/lewis-on-the-necessity-of-the-past.html'},
      'no-new-reading-for-oct-7.html': { type: 'html', url: '/670f2010/readings/no-new-reading-for-oct-7.html'},
      'reading-for-last-week.html': { type: 'html', url: '/670f2010/readings/reading-for-last-week.html'},
      'reading-for-nov-2.html': { type: 'html', url: '/670f2010/readings/reading-for-nov-2.html'},
      'reading-for-nov-9.html': { type: 'html', url: '/670f2010/readings/reading-for-nov-9.html'},
      'reading-for-oct-19.html': { type: 'html', url: '/670f2010/readings/reading-for-oct-19.html'},
      'reading-for-Oct-26.html': { type: 'html', url: '/670f2010/readings/reading-for-Oct-26.html'},
      'reading-for-oct-5.html': { type: 'html', url: '/670f2010/readings/reading-for-oct-5.html'},
      'readings-for-09-28.html': { type: 'html', url: '/670f2010/readings/readings-for-09-28.html'},
      'readings-for-09-30.html': { type: 'html', url: '/670f2010/readings/readings-for-09-30.html'},
      'readings-for-10-14.html': { type: 'html', url: '/670f2010/readings/readings-for-10-14.html'},
      'readings-for-nov-16.html': { type: 'html', url: '/670f2010/readings/readings-for-nov-16.html'},
      'readings-for-Nov-18th.html': { type: 'html', url: '/670f2010/readings/readings-for-Nov-18th.html'},
      'readings-for-oct-28.html': { type: 'html', url: '/670f2010/readings/readings-for-oct-28.html'},
      'readings-on-omnipotence.html': { type: 'html', url: '/670f2010/readings/readings-on-omnipotence.html'},
      'readings-on-omniscience.html': { type: 'html', url: '/670f2010/readings/readings-on-omniscience.html'},
    }},
    'SEIs-and-eternity.html': { type: 'html', url: '/670f2010/SEIs-and-eternity.html'},
    'syllabus.html': { type: 'html', url: '/670f2010/syllabus.html'},
    'updated-course-description.html': { type: 'html', url: '/670f2010/updated-course-description.html'},
  }},
  '863w2010': { type: 'dir', contents: {
    'discussion': { type: 'dir', contents: {
      'index.html': { type: 'html', url: '/863w2010/discussion/index.html'},
      'open-thread.html': { type: 'html', url: '/863w2010/discussion/open-thread.html'},
    }},
    'for-class': { type: 'dir', contents: {
      'for-feb-16.html': { type: 'html', url: '/863w2010/for-class/for-feb-16.html'},
      'for-feb-2.html': { type: 'html', url: '/863w2010/for-class/for-feb-2.html'},
      'for-feb-9.html': { type: 'html', url: '/863w2010/for-class/for-feb-9.html'},
      'for-jan-26.html': { type: 'html', url: '/863w2010/for-class/for-jan-26.html'},
      'for-mar-5.html': { type: 'html', url: '/863w2010/for-class/for-mar-5.html'},
      'index.html': { type: 'html', url: '/863w2010/for-class/index.html'},
      'post1.html': { type: 'html', url: '/863w2010/for-class/post1.html'},
      'post2.html': { type: 'html', url: '/863w2010/for-class/post2.html'},
      'post4.html': { type: 'html', url: '/863w2010/for-class/post4.html'},
    }},
    'index.html': { type: 'html', url: '/863w2010/index.html'},
    'news': { type: 'dir', contents: {
      'comments-broken.html': { type: 'html', url: '/863w2010/news/comments-broken.html'},
      'comments-now-available.html': { type: 'html', url: '/863w2010/news/comments-now-available.html'},
      'index.html': { type: 'html', url: '/863w2010/news/index.html'},
      'post3.html': { type: 'html', url: '/863w2010/news/post3.html'},
      'rescheduling.html': { type: 'html', url: '/863w2010/news/rescheduling.html'},
    }},
    'readings.html': { type: 'html', url: '/863w2010/readings.html'},
    'supplementary-readings.html': { type: 'html', url: '/863w2010/supplementary-readings.html'},
    'syllabus.html': { type: 'html', url: '/863w2010/syllabus.html'},
  }},
  '999s2011': { type: 'dir', contents: {
    'index.html': { type: 'html', url: '/999s2011/index.html'},
    'on-what-to-present.html': { type: 'html', url: '/999s2011/on-what-to-present.html'},
    'preliminaries.html': { type: 'html', url: '/999s2011/preliminaries.html'},
    'sign-up.html': { type: 'html', url: '/999s2011/sign-up.html'},
    'some-books.html': { type: 'html', url: '/999s2011/some-books.html'},
    'syllabus.html': { type: 'html', url: '/999s2011/syllabus.html'},
  }},


  }},
  'gizmos': { type: 'dir', contents: {
    'index.html': { type: 'html', url: '/gizmos/index.html'},
    'iphonlets-bookmarklet.html': { type: 'html', url: '/gizmos/iphonlets-bookmarklet.html'},
    'osu-ezproxy-bookmarklet.html': { type: 'html', url: '/gizmos/osu-ezproxy-bookmarklet.html'},
    'pandoc-bundle-for-vim.html': { type: 'html', url: '/gizmos/pandoc-bundle-for-vim.html'},
    'rename_to_dot_htaccess.html': { type: 'html', url: '/gizmos/rename_to_dot_htaccess.html'},
    'textmate-bundle-for-pandoc.html': { type: 'html', url: '/gizmos/textmate-bundle-for-pandoc.html'},
    'unofficial-osu-philosophy-department-colloquia-calendar.html': { type: 'html', url: '/gizmos/unofficial-osu-philosophy-department-colloquia-calendar.html'},
  }},
  'index.html': { type: 'html', url: '/index.html'},
  'license.html': { type: 'html', url: '/license.html'},
  'me.html': { type: 'html', url: '/me.html'},
  'research': { type: 'dir', contents: {
    'arabic-liar.html': { type: 'html', url: '/research/arabic-liar.html'},
    'dissertation.html': { type: 'html', url: '/research/dissertation.html'},
    'index.html': { type: 'html', url: '/research/index.html'},
    'maximal-possibilities.html': { type: 'html', url: '/research/maximal-possibilities.html'},
    'once-present.html': { type: 'html', url: '/research/once-present.html'},
    'presentism-and-truthmaking.html': { type: 'html', url: '/research/presentism-and-truthmaking.html'},
    'way-things-were.html': { type: 'html', url: '/research/way-things-were.html'},
  }},
  'site.html': { type: 'html', url: '/site.html'},
}}
